{% set name = "ibis-omniscidb" %}
{% set version = "2.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b16b1d0a5186c2e7d7d423790cb0bafb8d0ee591473f0ecb914f295cd944dc7b

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools-scm
    - wheel
  run:
    - python >={{ python_min }}
    - ibis-framework-core >2.0
    - geopandas
    - pyarrow
    - pandas
    - pyomnisci >=0.28.1
    - regex
    - rbc >=0.4.0
    - shapely

test:
  requires:
    - python {{ python_min }}
  imports:
    - ibis_omniscidb

about:
  home: https://github.com/omnisci/ibis-omniscidb
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: OmniSciDB backend for Ibis-Framework
  description: |
    Ibis is a Python framework to write data analytics code, in a similar way to pandas. 
    Ibis can execute the queries not only in memory (as pandas does), but in different backends,
    including SQL databases, and analytics databases, like OmniSciDB.
    OmniSciDB is SQL-based, relational, columnar and specifically developed to harness the massive 
    parallelism of modern CPU and GPU hardware. OmniSciDB can query up to billions of rows in 
    milliseconds, and is capable of unprecedented ingestion speeds, making it the ideal SQL engine 
    for the era of big, high-velocity data.
  doc_url: https://github.com/omnisci/ibis-omniscidb
  dev_url: https://github.com/omnisci/ibis-omniscidb

extra:
  recipe-maintainers:
    - xmnlab
    - guilhermeleobas
